name: Daily Image Update

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update background image URL
        run: |
          node scripts/update-image.js
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update background image URL $(date -u)"
          git push origin HEAD:main
