name: Daily Quote Update

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update daily quote
        run: node scripts/update-quote.js
